[package]
name = "expandr-semantic"
description = "expandr subpackage that handles expansion of the AST"
version.workspace = true
edition.workspace = true

[dependencies]
expandr-syntax = { path = "../syntax" }
thiserror = "2.0.17"
color-print = "0.3.7"
