[package]
name = "expandr-driver"
version.workspace = true
edition.workspace = true

[dependencies]
expandr-syntax   = { path = "../syntax" }
expandr-semantic = { path = "../semantic" }
thiserror = "2.0.17"
