[workspace]
resolver = "2"

default-members = [
   "bin/expandr"
]
members = [
    "crates/syntax",
    "crates/semantic",
    "crates/driver",
    "crates/lsp",
    "bin/expandr",
]

# Inherited by sub-packages
[workspace.package]
version = "0.1.0"
edition = "2021"

