[package]
name = "expandr"
description = "Cli interface for the expandr language"
version.workspace = true
edition.workspace = true

[dependencies]
expandr-driver = { path = "../../crates/driver" }

clap = { version = "4.5.53", features = ["derive"] }
anstream = "0.6.20"
color-print = "0.3.7"
anyhow = "1.0.100"
