[package]
name = "expandr-syntax"
description = "expandr subpackage that handles parsing"
version.workspace = true
edition.workspace = true

[dependencies]
logos = "0.14.2"
thiserror = "2.0.17"
color-print = "0.3.7"
